language: php

php:
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.3

env:
  - CONFIG=test

script: phpunit -d session.name=test -c ./test/phpunit.xml --log-junit ./report/logfile.xml --coverage-html ./report/coverage-html/
